on:
  workflow_run:
    workflows: ["gefs_osn"]
    types: [completed]
  workflow_dispatch:

name: gefs_osn_stage3

jobs:
  docker:
    runs-on: ubuntu-latest #self-hosted
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
      AWS_REQUEST_CHECKSUM_CALCULATION: when_required
      AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
    permissions:
     contents: write
    container: rocker/geospatial:latest
    steps:
      - uses: actions/checkout@v6

      - name: clone lake repository
        uses: actions/checkout@v6
        with:
          repository: ecoforecastVT/YARR-forecast
          token: ${{ secrets.GIT_PAT }}
          path: forecast-code

      - name: Install libuv
        shell: bash
        run: |
          apt-get update
          apt-get install -y libuv1 libuv1-dev

      - name: Install
        shell: Rscript {0}
        run: |
          install.packages("remotes")
          remotes::install_github("eco4cast/gefs4cast")
          remotes::install_github("cboettig/duckdbfs")
          remotes::install_github("appelmar/gdalcubes")
          install.packages("minioclient")
          install.packages("decor")
          install.packages("imputeTS")
          install.packages("future")
          install.packages("furrr")
          #remotes::install_version("arrow", version = "20.0.0")

      - name: Download Pseudo
        shell: Rscript {0}
        run: source("forecast-code/drivers/download_psuedo.R")

      - name: Update Stage3
        shell: Rscript {0}
        run: source("forecast-code/drivers/update_stage3.R")

      - name: Call Healthcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -m 10 --retry 5 https://hc-ping.com/4d04c0e6-f810-45ae-80d7-dec2f89d0617
