on:
  schedule:
   - cron: "0 5 * * *"
  workflow_dispatch:


name: inflows

jobs:
  run_inflows:
    runs-on: ubuntu-latest #[self-hosted]
    env:
      GITHUB_PAT: ${{ secrets.GIT_TOKEN }}
      MW_ACCESS_KEY_ID: ${{ secrets.MW_ACCESS_KEY_ID }}
      MW_ACCESS_SECRET: ${{ secrets.MW_ACCESS_SECRET }}
    permissions:
     contents: write
    container: rqthomas/flare-rocker:4.4
    steps:
      - uses: actions/checkout@v6

      - name: clone lake repository
        uses: actions/checkout@v6
        with:
          repository: ecoforecastVT/YARR-forecast
          token: ${{ secrets.GIT_PAT }}
          path: forecast-code

      - name: Install
        shell: Rscript {0}
        run: |
          install.packages("remotes")
          install.packages("minioclient")
          install.packages("tidymodels")
          #remotes::install_version("arrow", version = "20.0.0")
          install.packages('xgboost')
          install.packages('RcppRoll')

      - name: Run Inflow Generation
        shell: Rscript {0}
        run: source("forecast-code/workflows/glm_aed_flare_automation_test/create_all_inflow_forecast_scenarios.R")
