on:
  schedule:
     - cron: '0 7 * * *'
  workflow_dispatch:


name: targets

jobs:
  generate_targets:
    runs-on: ubuntu-latest #[self-hosted]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.MW_ACCESS_KEY_ID }}
      OSN_SECRET: ${{ secrets.MW_ACCESS_SECRET }}
      MW_ACCESS_KEY_ID: ${{ secrets.MW_ACCESS_KEY_ID }}
      MW_ACCESS_SECRET: ${{ secrets.MW_ACCESS_SECRET }}
      MW_FTP_USER: ${{ secrets.MW_FTP_USER }}
      MW_FTP_URL: ${{ secrets.MW_FTP_URL }}
    permissions:
     contents: write
    container: rqthomas/flare-rocker:4.4
    steps:
      - uses: actions/checkout@v6

      - name: clone lake repository
        uses: actions/checkout@v6
        with:
          repository: ecoforecastVT/YARR-forecast
          token: ${{ secrets.GIT_PAT }}
          path: forecast-code

      - name: Install
        shell: Rscript {0}
        run: |
          install.packages("remotes")
          install.packages("minioclient")
          install.packages('RcppRoll')
          install.packages('RCurl')
          install.packages('here')
          install.packages('jsonlite')

      - name: Run Targets Generation
        shell: Rscript {0}
        run: source("forecast-code/workflows/glm_aed_flare_automation_test/generate_targets_aed_alternative.R")

      - name: Call Healthcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -m 10 --retry 5 https://hc-ping.com/f7eaffe5-8aa1-4bc9-be14-3aa11a799cbb
