on:
  workflow_run:
    workflows: ["gefs_osn_stage3"]
    types: [completed]
  workflow_dispatch:

# on:
#   workflow_dispatch:
#   schedule:
#    - cron: "0 13 * * *"

name: glm_aed_flare_automation_test

jobs:
  run_flare:
    runs-on: ubuntu-latest #[self-hosted]
    env:
      GITHUB_PAT: ${{ secrets.GIT_TOKEN }}
      MW_ACCESS_KEY_ID: ${{ secrets.MW_ACCESS_KEY_ID }}
      MW_ACCESS_SECRET: ${{ secrets.MW_ACCESS_SECRET }}
    permissions:
     contents: write
    container: rqthomas/flare-rocker:4.4
    steps:
      - uses: actions/checkout@v6

      - name: clone lake repository
        uses: actions/checkout@v6
        with:
          repository: ecoforecastVT/YARR-forecast
          token: ${{ secrets.GIT_PAT }}
          path: forecast-code

      - name: install deps
        env:
          GITHUB_PAT: ${{ secrets.GIT_TOKEN }}
        shell: Rscript {0}
        run: |
          remotes::install_github('LTREB-reservoirs/ver4castHelpers')
          remotes::install_github('FLARE-forecast/ropenmeteo')
          install.packages('rLakeAnalyzer')
          install.packages('minioclient')
          install.packages('forecast')
          install.packages('fable')
          install.packages('tsibble')

# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MW_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MW_ACCESS_SECRET }}
          GITHUB_PAT: ${{ secrets.GIT_TOKEN }}
        run:  Rscript $GITHUB_WORKSPACE/forecast-code/workflows/glm_aed_flare_automation_test/forecast_workflow_aed.R

      - name: Call Healthcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -m 10 --retry 5 https://hc-ping.com/a880a405-7e69-40cb-96f0-8f0e10eebc8c
