# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  #schedule:
  #  - cron: '0 15 * * *'
  workflow_dispatch:

name: scoring

jobs:
  docker:
    runs-on: ubuntu-latest #[self-hosted]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      MW_ACCESS_KEY_ID: ${{ secrets.MW_ACCESS_KEY_ID }}
      MW_ACCESS_SECRET: ${{ secrets.MW_ACCESS_SECRET }}
    permissions:
     contents: write
    container: rqthomas/flare-rocker:4.4
    steps:
      - uses: actions/checkout@v6

      - name: clone lake repository
        uses: actions/checkout@v6
        with:
          repository: ecoforecastVT/YARR-forecast
          token: ${{ secrets.GIT_PAT }}
          path: forecast-code

      - name: install deps
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        shell: Rscript {0}
        run: |
          remotes::install_github('LTREB-reservoirs/ver4castHelpers')
          install.packages('rLakeAnalyzer')
          install.packages('minioclient')

      - name: scoring-prep
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MW_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MW_ACCESS_SECRET }}
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: Rscript $GITHUB_WORKSPACE/forecast-code/scoring/prep-scoring.R

      - name: scoring-prep
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MW_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MW_ACCESS_SECRET }}
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: Rscript $GITHUB_WORKSPACE/forecast-code/scoring/scoring.R
